/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * .env config for schema validator
 */
export interface ValidatorDotEnvConfigSchema {
  /**
   * use this envvar to control load-time verbosity
   */
  VALIDATED_CONFIG_STRICTNESS_LEVEL?: "full" | "warn" | "none";
  [k: string]: unknown;
}
